// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjafivptbizdrzkozonv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqYWZpdnB0Yml6ZHJ6a296b252Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NzY1NjUsImV4cCI6MjA3MjM1MjU2NX0.GxUFl9wsRSmQdcCc0xBAfOYpw4BpSToBSaW2gP63Rig";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});